# Generated by Django 4.0.3 on 2022-04-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_alter_users_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='otp_used',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
