# Generated by Django 4.0.3 on 2022-04-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0006_alter_users_dl_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dl_image',
            field=models.CharField(max_length=200),
        ),
    ]
