# Generated by Django 4.0.3 on 2022-04-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0007_alter_users_dl_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_admin',
            field=models.IntegerField(default=0),
        ),
    ]
