# Generated by Django 4.0.3 on 2022-04-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0009_alter_users_otp_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loctoin_id',
            new_name='loction_id',
        ),
    ]
