# Generated by Django 4.0.3 on 2022-04-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0010_rename_loctoin_id_location_loction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='comany_name',
            new_name='company_name',
        ),
    ]
