# Generated by Django 4.0.3 on 2022-04-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0013_rename_loction_id_location_location_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
