# Generated by Django 4.0.3 on 2022-04-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0015_alter_booking_from_date_alter_booking_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
