# Generated by Django 4.0.3 on 2022-04-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0016_alter_booking_from_date_alter_booking_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('feedbacks_id', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion_date', models.DateField()),
                ('suggestion', models.CharField(max_length=200)),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_site.users')),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
    ]
