# Generated by Django 4.0.3 on 2022-04-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0018_rename_booking_status_booking_payment_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='locaton',
        ),
    ]
