# Generated by Django 4.0.3 on 2022-04-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0019_alter_location_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
    ]
