# Generated by Django 4.0.3 on 2022-04-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0020_alter_location_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pick_drop_charge',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='refund_amt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
