# Generated by Django 3.0.5 on 2022-09-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0021_car_pick_drop_charge_car_refund_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_verify',
            field=models.IntegerField(default=0),
        ),
    ]
