# Generated by Django 3.0.5 on 2022-09-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0022_users_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_verify',
            field=models.IntegerField(),
        ),
    ]
