# Generated by Django 3.0.5 on 2022-10-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0025_payments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payments',
            table='payments',
        ),
    ]
