# Generated by Django 3.0.5 on 2022-10-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0026_auto_20221002_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancel_payment',
            fields=[
                ('cancel_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_number', models.BigIntegerField()),
                ('cancel_disc', models.CharField(max_length=500)),
                ('type_payment', models.CharField(max_length=20)),
                ('cancel_amount', models.FloatField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_site.booking')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_site.payments')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_site.users')),
            ],
        ),
        migrations.DeleteModel(
            name='feedbacks',
        ),
    ]
