# Generated by Django 3.0.5 on 2022-10-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0027_auto_20221014_1532'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cancel_payment',
            table='cancel payment',
        ),
    ]
